### PR TITLE
User Sign In

### PR DESCRIPTION
**Pull request by gschorkopf**
@bstd77 lemme know if you have questions. I'll be around. I've added some notes to the README for you to test this out. You'll want to make sure you do the following first:

* Check out this branch locally. You do that by going into your local roomloo directory and running `git fetch origin; git checkout -b gschorkopf/user-sign-in origin/gschorkopf/user-sign-in`
* Bundle the new gem (run `bundle`), and rake the DB (run `rake db:migrate`)
* Create a user and log in. I added this to the README

It's pretty simple so far. If you want to merge this branch into your main codebase, there's a bit green "merge pull request" button at the bottom here.

Some screenshots:

`/login`
screen shot 2015-04-01 at 4 51 26 pm

And then `/`
screen shot 2015-04-01 at 4 51 58 pm

### CODE REVIEW

**Comment by gschorkopf** [comment]
*hello darkness my old friend*

**Comment by gschorkopf** [comment]
@bstd77 consider checking out my series of commits here. Short, direct, and collected in a feature-specific pull request.

**Comment by bstd77** [comment]
Ok, so the commits are fairly granular. Useful to see. I'll start doing this I promise! haha

**Comment by gschorkopf** [comment]
Commits are the sentences in a paragraph. The paragraph is a branch. These
paragraphs amass to an amazing story. Your app

**Comment by bstd77** [comment]
beautiful.

**Pull request closed without merging**
